import BootstrapClient from './components/BootstrapClient';

export default function Page() {
  return (
    <>
      <div className="container">
        <header>
          <div className="header-top">
            <div className="header-right">
              <button id="settings-btn" className="btn btn-settings">Settings</button>
              <div className="schedule-actions">
                <button id="save-btn" className="btn btn-icon-small has-icon" title="Save Schedule">
                  <img src="/images/savelogo.png" alt="Save Schedule" />
                </button>
                <button id="load-btn" className="btn btn-icon-small has-icon" title="Load Schedule">
                  <img src="/images/openlogo.png" alt="Load Schedule" />
                </button>
              </div>
            </div>
          </div>
          <div className="title-section">
            <div className="logo-section">
              <img src="/images/FFlogo.jpg" alt="FF Logo" className="app-logo" />
            </div>
            <h1 id="schedule-title">Wedding Day Beauty Schedule</h1>
          </div>
          <p id="schedule-subtitle" className="schedule-subtitle"></p>
          <div className="controls">
            <button id="add-client-btn" className="btn btn-primary">Add Guest</button>
            <button id="add-artist-btn" className="btn btn-secondary">Add Artist</button>
            <button id="export-btn" className="btn btn-success">Export Schedule</button>
          </div>
        </header>

        <div className="schedule-container">
          <div className="time-column">
            <div className="time-header">Time</div>
            <div className="time-slots" id="time-slots">
              {/* Time slots will be generated by JavaScript */}
            </div>
          </div>
          
          <div className="artists-container" id="artists-container">
            {/* Artist columns will be generated by JavaScript */}
          </div>
        </div>
      </div>

      {/* Add Guest Modal */}
      <div id="add-client-modal" className="modal">
        <div className="modal-content">
          <span className="close">&times;</span>
          <h2>Add New Guest</h2>
          <form id="client-form">
            <label htmlFor="client-name">Guest Name:</label>
            <input type="text" id="client-name" required />
            
            <label>Services:</label>
            <div className="checkbox-group">
              <label><input type="checkbox" id="makeup" value="makeup" /> Makeup</label>
              <label><input type="checkbox" id="hair" value="hair" /> Hair Styling</label>
            </div>
            
            <label htmlFor="client-color">Guest Color:</label>
            <div className="color-input-group">
              <input type="color" id="client-color" defaultValue="#ff6b6b" />
              <div className="color-swatch" id="color-swatch"></div>
            </div>
            
            <button type="button" id="add-guest-btn">Add Guest</button>
          </form>
        </div>
      </div>

      {/* Add Artist Modal */}
      <div id="artist-modal" className="modal">
        <div className="modal-content">
          <span className="close">&times;</span>
          <h2>Add New Artist</h2>
          <form id="artist-form">
            <div className="form-group">
              <label htmlFor="artist-name">Artist Name:</label>
              <input type="text" id="artist-name" required />
            </div>
            <div className="form-group">
              <label htmlFor="artist-specialty">Specialty:</label>
              <select id="artist-specialty" required>
                <option value="">Select Specialty</option>
                <option value="makeup">Makeup</option>
                <option value="hair">Hair Styling</option>
              </select>
            </div>
            <button type="submit" className="btn btn-primary">Add Artist</button>
          </form>
        </div>
      </div>

      {/* Settings Modal */}
      <div id="settings-modal" className="modal">
        <div className="modal-content">
          <span className="close">&times;</span>
          <div className="modal-body">
            <h2>Settings</h2>
            <h3>Wedding Details</h3>
            <div className="form-group">
              <label>Bride's Name:</label>
              <input type="text" id="settings-bride-name" placeholder="Enter Bride's Name" />
            </div>
            <div className="form-group">
              <label>Wedding Date:</label>
              <input type="date" id="settings-wedding-date" />
            </div>
            <div className="form-group">
              <label>Location:</label>
              <input type="text" id="settings-location" placeholder="Enter Location" />
            </div>
            <div className="form-group">
              <label>Bride Ready Time:</label>
              <input type="time" id="settings-bride-ready-time" defaultValue="11:00" />
            </div>
            
            <h3>Duration Settings</h3>
            <div className="duration-settings">
              <div className="duration-row">
                <label>Bride Makeup:</label>
                <input type="number" id="settings-bride-makeup-duration" defaultValue="90" min="15" max="180" /> min
              </div>
              <div className="duration-row">
                <label>
                  <input type="checkbox" id="settings-bride-hair-two-parts" /> 
                  Bride's hair is done in 2 parts
                </label>
              </div>
              <div className="duration-row" id="bride-hair-single-row">
                <label>Bride Hair:</label>
                <input type="number" id="settings-bride-hair-duration" defaultValue="90" min="15" max="180" /> min
              </div>
              <div className="duration-row" id="bride-hair-part1-row" style={{ display: 'none' }}>
                <label>Bride's Hair Part I:</label>
                <input type="number" id="settings-bride-hair-part1-duration" defaultValue="60" min="15" max="120" /> min
              </div>
              <div className="duration-row" id="bride-hair-part2-row" style={{ display: 'none' }}>
                <label>Bride's Hair Part II:</label>
                <input type="number" id="settings-bride-hair-part2-duration" defaultValue="30" min="15" max="120" /> min
              </div>
              <div className="duration-row">
                <label>Guest Makeup:</label>
                <input type="number" id="settings-guest-makeup-duration" defaultValue="45" min="15" max="120" /> min
              </div>
              <div className="duration-row">
                <label>Guest Hair:</label>
                <input type="number" id="settings-guest-hair-duration" defaultValue="45" min="15" max="120" /> min
              </div>
            </div>
          </div>
          <div className="modal-footer">
            <button id="save-settings-btn" className="btn btn-primary">Save Settings</button>
          </div>
        </div>
      </div>

      {/* Save Schedule Modal */}
      <div id="save-modal" className="modal">
        <div className="modal-content">
          <span className="close">&times;</span>
          <div className="modal-body">
            <h2>Save Schedule</h2>
            <div className="form-group">
              <label>Schedule Name:</label>
              <input type="text" id="save-schedule-name" placeholder="Enter schedule name (e.g., Sarah's Wedding)" />
            </div>
            <div id="existing-schedules" className="existing-schedules">
              <h3>Existing Schedules:</h3>
              <div id="schedules-list"></div>
            </div>
          </div>
          <div className="modal-footer">
            <button id="save-schedule-btn" className="btn btn-primary">Save Schedule</button>
          </div>
        </div>
      </div>

      {/* Load Schedule Modal */}
      <div id="load-modal" className="modal">
        <div className="modal-content">
          <span className="close">&times;</span>
          <div className="modal-body">
            <h2>Load Schedule</h2>
            <div id="load-schedules-list" className="schedules-list">
              {/* Schedules will be populated here */}
            </div>
            <div className="no-schedules" id="no-schedules" style={{ display: 'none' }}>
              <p>No saved schedules found. Create and save a schedule first!</p>
            </div>
          </div>
          <div className="modal-footer">
            <button id="close-load-modal" className="btn btn-secondary">Close</button>
          </div>
        </div>
      </div>

      {/* Load the client-side logic after hydration */}
      <BootstrapClient />
    </>
  );
}
